/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedLabsRouteImport } from './routes/_authenticated/labs'
import { Route as AuthenticatedInstructorRouteImport } from './routes/_authenticated/instructor'
import { Route as AuthenticatedGraphRouteImport } from './routes/_authenticated/graph'
import { Route as AuthenticatedFoundationRouteImport } from './routes/_authenticated/foundation'
import { Route as AuthenticatedEnterpriseRouteImport } from './routes/_authenticated/enterprise'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyRouteImport } from './routes/_authenticated/daily'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedCareerRouteImport } from './routes/_authenticated/career'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedFoundationIndexRouteImport } from './routes/_authenticated/foundation.index'
import { Route as AuthenticatedCehv13IndexRouteImport } from './routes/_authenticated/cehv13.index'
import { Route as AuthenticatedSessionSlugRouteImport } from './routes/_authenticated/session.$slug'
import { Route as AuthenticatedMonthNumberRouteImport } from './routes/_authenticated/month.$number'
import { Route as AuthenticatedFoundationTopicRouteImport } from './routes/_authenticated/foundation.$topic'
import { Route as AuthenticatedCehv13ModuleRouteImport } from './routes/_authenticated/cehv13.$module'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabsRoute = AuthenticatedLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstructorRoute = AuthenticatedInstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGraphRoute = AuthenticatedGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoundationRoute = AuthenticatedFoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnterpriseRoute = AuthenticatedEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyRoute = AuthenticatedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareerRoute = AuthenticatedCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoundationIndexRoute =
  AuthenticatedFoundationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFoundationRoute,
  } as any)
const AuthenticatedCehv13IndexRoute =
  AuthenticatedCehv13IndexRouteImport.update({
    id: '/cehv13/',
    path: '/cehv13/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionSlugRoute =
  AuthenticatedSessionSlugRouteImport.update({
    id: '/session/$slug',
    path: '/session/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonthNumberRoute =
  AuthenticatedMonthNumberRouteImport.update({
    id: '/month/$number',
    path: '/month/$number',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoundationTopicRoute =
  AuthenticatedFoundationTopicRouteImport.update({
    id: '/$topic',
    path: '/$topic',
    getParentRoute: () => AuthenticatedFoundationRoute,
  } as any)
const AuthenticatedCehv13ModuleRoute =
  AuthenticatedCehv13ModuleRouteImport.update({
    id: '/cehv13/$module',
    path: '/cehv13/$module',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/career': typeof AuthenticatedCareerRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enterprise': typeof AuthenticatedEnterpriseRoute
  '/foundation': typeof AuthenticatedFoundationRouteWithChildren
  '/graph': typeof AuthenticatedGraphRoute
  '/instructor': typeof AuthenticatedInstructorRoute
  '/labs': typeof AuthenticatedLabsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/cehv13/$module': typeof AuthenticatedCehv13ModuleRoute
  '/foundation/$topic': typeof AuthenticatedFoundationTopicRoute
  '/month/$number': typeof AuthenticatedMonthNumberRoute
  '/session/$slug': typeof AuthenticatedSessionSlugRoute
  '/cehv13/': typeof AuthenticatedCehv13IndexRoute
  '/foundation/': typeof AuthenticatedFoundationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/career': typeof AuthenticatedCareerRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enterprise': typeof AuthenticatedEnterpriseRoute
  '/graph': typeof AuthenticatedGraphRoute
  '/instructor': typeof AuthenticatedInstructorRoute
  '/labs': typeof AuthenticatedLabsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/cehv13/$module': typeof AuthenticatedCehv13ModuleRoute
  '/foundation/$topic': typeof AuthenticatedFoundationTopicRoute
  '/month/$number': typeof AuthenticatedMonthNumberRoute
  '/session/$slug': typeof AuthenticatedSessionSlugRoute
  '/cehv13': typeof AuthenticatedCehv13IndexRoute
  '/foundation': typeof AuthenticatedFoundationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/career': typeof AuthenticatedCareerRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/daily': typeof AuthenticatedDailyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enterprise': typeof AuthenticatedEnterpriseRoute
  '/_authenticated/foundation': typeof AuthenticatedFoundationRouteWithChildren
  '/_authenticated/graph': typeof AuthenticatedGraphRoute
  '/_authenticated/instructor': typeof AuthenticatedInstructorRoute
  '/_authenticated/labs': typeof AuthenticatedLabsRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/cehv13/$module': typeof AuthenticatedCehv13ModuleRoute
  '/_authenticated/foundation/$topic': typeof AuthenticatedFoundationTopicRoute
  '/_authenticated/month/$number': typeof AuthenticatedMonthNumberRoute
  '/_authenticated/session/$slug': typeof AuthenticatedSessionSlugRoute
  '/_authenticated/cehv13/': typeof AuthenticatedCehv13IndexRoute
  '/_authenticated/foundation/': typeof AuthenticatedFoundationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assessments'
    | '/career'
    | '/certificates'
    | '/daily'
    | '/dashboard'
    | '/enterprise'
    | '/foundation'
    | '/graph'
    | '/instructor'
    | '/labs'
    | '/notes'
    | '/profile'
    | '/resources'
    | '/roadmap'
    | '/skills'
    | '/cehv13/$module'
    | '/foundation/$topic'
    | '/month/$number'
    | '/session/$slug'
    | '/cehv13/'
    | '/foundation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assessments'
    | '/career'
    | '/certificates'
    | '/daily'
    | '/dashboard'
    | '/enterprise'
    | '/graph'
    | '/instructor'
    | '/labs'
    | '/notes'
    | '/profile'
    | '/resources'
    | '/roadmap'
    | '/skills'
    | '/cehv13/$module'
    | '/foundation/$topic'
    | '/month/$number'
    | '/session/$slug'
    | '/cehv13'
    | '/foundation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assessments'
    | '/_authenticated/career'
    | '/_authenticated/certificates'
    | '/_authenticated/daily'
    | '/_authenticated/dashboard'
    | '/_authenticated/enterprise'
    | '/_authenticated/foundation'
    | '/_authenticated/graph'
    | '/_authenticated/instructor'
    | '/_authenticated/labs'
    | '/_authenticated/notes'
    | '/_authenticated/profile'
    | '/_authenticated/resources'
    | '/_authenticated/roadmap'
    | '/_authenticated/skills'
    | '/_authenticated/cehv13/$module'
    | '/_authenticated/foundation/$topic'
    | '/_authenticated/month/$number'
    | '/_authenticated/session/$slug'
    | '/_authenticated/cehv13/'
    | '/_authenticated/foundation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labs': {
      id: '/_authenticated/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof AuthenticatedLabsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructor': {
      id: '/_authenticated/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof AuthenticatedInstructorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/graph': {
      id: '/_authenticated/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AuthenticatedGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foundation': {
      id: '/_authenticated/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof AuthenticatedFoundationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enterprise': {
      id: '/_authenticated/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof AuthenticatedEnterpriseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily': {
      id: '/_authenticated/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthenticatedDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career': {
      id: '/_authenticated/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AuthenticatedCareerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foundation/': {
      id: '/_authenticated/foundation/'
      path: '/'
      fullPath: '/foundation/'
      preLoaderRoute: typeof AuthenticatedFoundationIndexRouteImport
      parentRoute: typeof AuthenticatedFoundationRoute
    }
    '/_authenticated/cehv13/': {
      id: '/_authenticated/cehv13/'
      path: '/cehv13'
      fullPath: '/cehv13/'
      preLoaderRoute: typeof AuthenticatedCehv13IndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session/$slug': {
      id: '/_authenticated/session/$slug'
      path: '/session/$slug'
      fullPath: '/session/$slug'
      preLoaderRoute: typeof AuthenticatedSessionSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/month/$number': {
      id: '/_authenticated/month/$number'
      path: '/month/$number'
      fullPath: '/month/$number'
      preLoaderRoute: typeof AuthenticatedMonthNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foundation/$topic': {
      id: '/_authenticated/foundation/$topic'
      path: '/$topic'
      fullPath: '/foundation/$topic'
      preLoaderRoute: typeof AuthenticatedFoundationTopicRouteImport
      parentRoute: typeof AuthenticatedFoundationRoute
    }
    '/_authenticated/cehv13/$module': {
      id: '/_authenticated/cehv13/$module'
      path: '/cehv13/$module'
      fullPath: '/cehv13/$module'
      preLoaderRoute: typeof AuthenticatedCehv13ModuleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFoundationRouteChildren {
  AuthenticatedFoundationTopicRoute: typeof AuthenticatedFoundationTopicRoute
  AuthenticatedFoundationIndexRoute: typeof AuthenticatedFoundationIndexRoute
}

const AuthenticatedFoundationRouteChildren: AuthenticatedFoundationRouteChildren =
  {
    AuthenticatedFoundationTopicRoute: AuthenticatedFoundationTopicRoute,
    AuthenticatedFoundationIndexRoute: AuthenticatedFoundationIndexRoute,
  }

const AuthenticatedFoundationRouteWithChildren =
  AuthenticatedFoundationRoute._addFileChildren(
    AuthenticatedFoundationRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedCareerRoute: typeof AuthenticatedCareerRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedDailyRoute: typeof AuthenticatedDailyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnterpriseRoute: typeof AuthenticatedEnterpriseRoute
  AuthenticatedFoundationRoute: typeof AuthenticatedFoundationRouteWithChildren
  AuthenticatedGraphRoute: typeof AuthenticatedGraphRoute
  AuthenticatedInstructorRoute: typeof AuthenticatedInstructorRoute
  AuthenticatedLabsRoute: typeof AuthenticatedLabsRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedCehv13ModuleRoute: typeof AuthenticatedCehv13ModuleRoute
  AuthenticatedMonthNumberRoute: typeof AuthenticatedMonthNumberRoute
  AuthenticatedSessionSlugRoute: typeof AuthenticatedSessionSlugRoute
  AuthenticatedCehv13IndexRoute: typeof AuthenticatedCehv13IndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedCareerRoute: AuthenticatedCareerRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedDailyRoute: AuthenticatedDailyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnterpriseRoute: AuthenticatedEnterpriseRoute,
  AuthenticatedFoundationRoute: AuthenticatedFoundationRouteWithChildren,
  AuthenticatedGraphRoute: AuthenticatedGraphRoute,
  AuthenticatedInstructorRoute: AuthenticatedInstructorRoute,
  AuthenticatedLabsRoute: AuthenticatedLabsRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedCehv13ModuleRoute: AuthenticatedCehv13ModuleRoute,
  AuthenticatedMonthNumberRoute: AuthenticatedMonthNumberRoute,
  AuthenticatedSessionSlugRoute: AuthenticatedSessionSlugRoute,
  AuthenticatedCehv13IndexRoute: AuthenticatedCehv13IndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
